---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[java]
      - recipe[golang]
      - recipe[rbenv]
      - recipe[rbenv::ruby_build]
      - recipe[yum-epel]
    attributes:
      java:
        jdk_version: 7
      rbenv:
        user: "vagrant"
        group: "vagrant"
